### ISSUE TITLE
training strategy

### ISSUE THREAD

**Issue by ssli23** [jiangqy/DPSH-pytorch#7]
I am very interested in this code ,can you give me some advice  for a higher MAP based on your code?

**Comment by jiangqy** [comment]
What is your problem?

**Comment by ssli23** [comment]
> What is your problem?

In the paper based your code,the map of 8 bit hashing code can reach 71% in cifar10,but i just get 64%. Is there anything wrong ?

**Comment by jiangqy** [comment]
8 bits or 12 bits?

**Comment by ssli23** [comment]
sorry，12bits

**Comment by ssli23** [comment]
> 8 bits or 12 bits?

how I can get a better performance ？

**Comment by weiyao0721** [comment]
> 
> 
> > What is your problem?
> 
> In the paper based your code,the map of 8 bit hashing code can reach 71% in cifar10,but i just get 64%. Is there anything wrong ?

I met the same problem with you, have you solved this problem later?

**Comment by weiyao0721** [comment]
> 
> 
> > What is your problem?
> 
> In the paper based your code,the map of 8 bit hashing code can reach 71% in cifar10,but i just get 64%. Is there anything wrong ?

I met the same problem when I try to reproduct the experiment of 12 bits hashing code, have you finished it later?
