### ISSUE TITLE
demo 

### ISSUE THREAD

**Issue by Zzz-zcy** [jiangqy/DPSH-pytorch#8]
I just started learning pytorch, how do I make a small demo that input two pictures to determine whether it is similar or not with your code ? Thank you .

**Comment by ssli23** [comment]
the code is demo already.you can change a small dataset instead to verify what you think。

**Comment by ssli23** [comment]
> I just started learning pytorch, how do I make a small demo that input two pictures to determine whether it is similar or not with your code ? Thank you .

the code is demo already.you can change a small dataset instead to verify what you think

**Comment by Zzz-zcy** [comment]
I want to load the trained model directly and test two of the images
